{{- $apiEnabled := .Values.api.enabled -}}
{{- $uiEnabled := .Values.ui.enabled -}}
{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "policyreporter.fullname" . }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
{{- range $key, $value := $.Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  annotations:
{{- range $key, $value := $.Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or $apiEnabled $uiEnabled }}
    - port: {{ .Values.global.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    {{- end }}
  selector:
    {{- include "policyreporter.selectorLabels" . | nindent 4 }}
{{- end }}
