name: Lint helm chart

on:
  push:
    # run pipeline on push on master
    branches:
      - main
      - development
    paths:
      - "charts/**"     
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: chart-testing (ct lint)
        uses: helm/chart-testing-action@v2.0.1

      - name: Helm Chart(helm)
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - uses: lra/setup-kubeval@v1
        with:
          version: 0.15.0

      - name: Run Helm Chart lint
        run: |
            ct lint --lint-conf=.github/ct_conf.yaml \
                    --chart-yaml-schema=.github/ct_chart_schema.yaml \
                    --target-branch=main --validate-maintainers=false \
                    --chart-dirs charts
